
$(function() {
  $('input.autocomplete').autocomplete({
    data: {
      "Android Development": null,
      "Apache Spark": null,
      "ASP.NET": null,
      "AWS": null,
      "C": null,
      "CakePHP": null,
      "Clojure": null,
      "CouchDB": null,
      "Data Science": null,
      "Django": null,
      "Elasticsearch": null,
      "Elm": null,
      "Express": null,
      "Flask": null,
      "Google Analytics": null,
      "GraphQL": null,
      "Gulp": null,
      "HTML 5": null,
      "Intro to Programming": null,
      "Java": null,
      "Jenkins": null,
      "Kotlin": null,
      "Latex": null,
      "Lisp": null,
      "MATLAB": null,
      "MySQL": null,
      "Perl": null,
      "Polymer": null,
      "Python": null,
      "React": null,
      "Regular Expressions": null,
      "Rust": null,
      "Scala": null,
      "Sketch": null,
      "SQL": null,
      "Unity": null,
      "Unity": null,
      "Vim": null,
      "WebGL": null,
      "Windows Server Administration": null,
      "Angular": null,
      "Assembly Language": null,
      "Bacbone.js": null,
      "C#": null,
      "Cassandra": null,
      "CoffeeScript": null,
      "CSS": null,
      "Data Structures": null,
      "Algorithms": null,
      "Docker": null,
      "Electron": null,
      "Emacs": null,
      "F#": null,
      "Git": null,
      "Google Cloud Platform": null,
      "Groovy": null,
      "Hadoop": null,
      "Illustrator": null,
      "Ionic": null,
      "Javascript": null,
      "jQuery": null,
      "Kubernetes": null,
      "LESS": null,
      "Lua": null,
      "Meteor.js": null,
      "Nginx": null,
      "Photoshop": null,
      "Prolog": null,
      "R": null,
      "React Native": null,
      "Ruby": null,
      "SAP ABAP": null,
      "SEO": null,
      "Smalltalk": null,
      "SQL Server": null,
      "Unreal Engine": null,
      "Visual Basic": null,
      "Webpack": null,
      "Wordpress": null,
      "Blogger": null,
      "Ansible": null,
      "Joomla": null,
      "Drupal": null,
      "Bootstrap": null,
      "AWK": null,
      "C++": null,
      "Chef": null,
      "CompTIA Certification": null,
      "D3.js": null,
      "Design Patterns": null,
      "ECMAScript": null,
      "Elixir": null,
      "Erlang": null,
      "Firebase": null,
      "Go": null,
      "Grails": null,
      "Growth Hacking": null,
      "Haskell": null,
      "Information Security & Hacking": null,
      "iOS and Swift": null,
      "Java Spring Framework": null,
      "Julia": null,
      "Laravel": null,
      "Linux System Administration": null,
      "Machine Learning": null,
      "MongoDB": null,
      "Node.js": null,
      "PHP": null,
      "Puppet": null,
      "Raspberry Pi": null,
      "Redis": null,
      "Ruby on Rails": null,
      "Sass": null,
      "Sinatra": null,
      "Socket.io": null,
      "TypeScript": null,
      "Vagrant": null,
      "Vue.js": null,
      "Website Performance": null,
      "Yii": null,
      "Google": 'https://placehold.it/250x250'
    },
    limit: 7, // The max amount of results that can be shown at once. Default: Infinity.
    onAutocomplete: function(val) {
      // Callback function when value is autcompleted.
    },
    minLength: 1, // The minimum length of the input for the autocomplete to start. Default: 1.
    });
  });